#!/bin/bash
#cat /root/.profile | grep -v contextNetServer > /tmp/tempprofile
#mv /tmp/tempprofile /root/.profile
#sed -i 's/GRUB_TIMEOUT=0/GRUB_TIMEOUT=5/g' /etc/default/grub
#update-grub

#sed -i 's|#ExecStart=-|ExecStart=-|g' /lib/systemd/system/getty@.service 
#sed -i '/^ExecStart=-\/sbin\/agetty --autologin/d' /lib/systemd/system/getty@.service
#sed -i 's|ExecStart=-/sbin/agetty --autologin|#ExecStart=-/sbin/agetty --autologin root --noclear %I $TERM|g' /lib/systemd/system/getty@.service
